export const salesOrderCreateSchema: any = {
  $schema: "http://json-schema.org/draft-07/schema#",
  title: "SalesOrderCreatePayload",
  description:
    "Schema for creating Sales Orders via /sap/opu/odata/sap/API_SALES_ORDER_SRV/A_SalesOrder including header, item, partner, and pricing data.",
  type: "object",
  properties: {
    output: {
      type: "object",
      properties: {
        SalesOrderType: { type: "string", description: 'Default "OR" if not provided' },
        SalesOrganization: { type: "string", description: 'Default "2001" if not provided' },
        DistributionChannel: { type: "string", description: 'Default "20" if not provided' },
        OrganizationDivision: { type: "string", description: 'Default "20" if not provided' },
        SalesGroup: { type: "string" },
        SalesOffice: { type: "string" },
        SalesDistrict: { type: "string" },
        SoldToParty: { type: "string", description: "SAP Customer placing the order from PO" },
        PurchaseOrderByCustomer: { type: "string" },
        CustomerPurchaseOrderDate: { type: "string", format: "ymdT00" },
        RequestedDeliveryDate: { type: "string", format: "ymdT00" },
        TransactionCurrency: { type: "string" },
        IncotermsClassification: { type: "string" },
        IncotermsTransferLocation: { type: "string" },
        CustomerPaymentTerms: { type: "string" },
        CustomerPriceGroup: { type: "string" },
        CustomerGroup: { type: "string" },
        OverallDeliveryStatus: { type: "string" },
        OverallBillingStatus: { type: "string" },
        SDDocumentReason: { type: "string" },
        PricingDate: { type: "string", format: "ymdT00" },
        ShippingCondition: { type: "string" },
        OverallTotalDeliveryStatus: { type: "string" },
        CustomerAccountAssignmentGroup: { type: "string" },
        CustomerPurchaseOrderType: { type: "string" },
        ReferenceSDDocument: { type: "string" },
        ReferenceSDDocumentCategory: { type: "string" },
        SalesOrderDate: { type: "string", format: "ymdT00" },

        to_Partner: {
          type: "array",
          description: "Header Partners",
          items: {
            type: "object",
            properties: {
              PartnerFunction: { type: "string", description: "Function (e.g., SP, SH, BP)" },
              Customer: { type: "string" },
              Supplier: { type: "string" },
              Personnel: { type: "string" },
              ContactPerson: { type: "string" },
            },
            required: ["PartnerFunction", "Customer"],
            additionalProperties: true,
          },
        },

        to_PricingElement: {
          type: "array",
          description: "Header Pricing Elements",
          items: {
            type: "object",
            properties: {
              PricingProcedureStep: { type: "string" },
              PricingProcedureCounter: { type: "string" },
              ConditionType: { type: "string" },
              PricingDateTime: { type: "string", format: "date-time" },
              ConditionAmount: { type: "number" },
              ConditionCurrency: { type: "string" },
              ConditionQuantity: { type: "number" },
              ConditionQuantityUnit: { type: "string" },
              ConditionScaleQuantity: { type: "number" },
              ConditionRateValue: { type: "number" },
              ConditionRateValueUnit: { type: "string" },
              ConditionCalculationType: { type: "string" },
              ConditionControl: { type: "string" },
              ConditionInactiveReason: { type: "string" },
              ConditionBaseValue: { type: "number" },
              ConditionIsForStatistics: { type: "boolean" },
            },
            required: ["PricingProcedureStep", "PricingProcedureCounter", "ConditionAmount"],
            additionalProperties: true,
          },
        },

        to_Item: {
          type: "array",
          description: "Sales Order Items",
          minItems: 1,
          items: {
            type: "object",
            properties: {
              SalesOrderItem: { type: "string" },
              Material: { type: "string" },
              MaterialByCustomer: { type: "string" },
              RequestedQuantity: { type: "number" },
              RequestedQuantityUnit: { type: "string" },
              Batch: { type: "string" },
              Plant: { type: "string" },
              StorageLocation: { type: "string" },
              ShippingPoint: { type: "string" },
              IncotermsClassification: { type: "string" },
              CustomerPaymentTerms: { type: "string" },
              SalesDocumentRjcnReason: { type: "string" },
              SDProcessStatus: { type: "string" },
              MaterialGroup: { type: "string" },
              ProfitCenter: { type: "string" },
              MaterialPricingGroup: { type: "string" },
              ProductHierarchy: { type: "string" },
              SalesOrderItemCategory: { type: "string" },
              ItemBillingBlockReason: { type: "string" },
              HigherLevelItem: { type: "string" },
              OrderQuantityUnit: { type: "string" },
              NetAmount: { type: "number", description: "Calculated by SAP" },
              TransactionCurrency: { type: "string", description: "Determined by SAP" },

              to_ItemPartner: {
                type: "array",
                description: "Item Partners",
                items: {
                  type: "object",
                  properties: {
                    PartnerFunction: { type: "string" },
                    Customer: { type: "string" },
                    Supplier: { type: "string" },
                    Personnel: { type: "string" },
                    ContactPerson: { type: "string" },
                  },
                  required: ["PartnerFunction", "Customer"],
                  additionalProperties: true,
                },
              },

              to_ItemPricingElement: {
                type: "array",
                description: "Item Pricing Elements",
                items: {
                  type: "object",
                  properties: {
                    PricingProcedureStep: { type: "string" },
                    PricingProcedureCounter: { type: "string" },
                    ConditionType: { type: "string" },
                    ConditionAmount: { type: "number" },
                    ConditionCurrency: { type: "string" },
                    ConditionQuantity: { type: "number" },
                    ConditionQuantityUnit: { type: "string" },
                    ConditionRateValue: { type: "number" },
                    ConditionRateValueUnit: { type: "string" },
                    ConditionScaleQuantity: { type: "number" },
                    ConditionCalculationType: { type: "string" },
                    ConditionControl: { type: "string" },
                    ConditionIsForStatistics: { type: "boolean" },
                  },
                  required: ["PricingProcedureStep", "PricingProcedureCounter", "ConditionAmount"],
                  additionalProperties: true,
                },
              },
            },
            additionalProperties: true,
          },
        },
      },
      required: [
        "SalesOrderType",
        "SalesOrganization",
        "DistributionChannel",
        "OrganizationDivision",
        "SoldToParty",
        "to_Item",
      ],
      additionalProperties: false,
    },
  },
  required: ["output"],
  additionalProperties: false,
};